### ISSUE TITLE
Laravel v9.0 / PHP 8.0 Roadmap

### ISSUE THREAD

**Issue by ahinkle** [ahinkle/laravel-resolvable-components#3]
- [ ] Add support for Laravel 9.
- [ ] Remove support for Laravel 7.
- [ ] Remove support for PHP to match Laravel 9 support.
- [ ] Review Code / make changes for PHP 8.0 support.
- [ ] Update (readme) documentation.
- [ ] Tag v2.0 release
